baseURL = 'https://example.org/'
languageCode = 'en-us'
theme = 'ananke'

DefaultContentLanguage = "sl"
sectionPagesMenu = 'main'
googleAnalytics = ""
enableRobotsTXT = true

[pagination]
pagerSize = 3

[languages]
[languages.sl]
title = "Ananke"
weight = 1
contentDir = "content/sl"
# languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 0
read_more_copy = "Več"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
